name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history and tags

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.11.0

      - name: Enable corepack (required for pnpm to register)
        run: corepack enable

      - name: 🔍 Debug Node + pnpm Environment
        run: |
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "PNPM version: $(pnpm -v)"
          echo "PNPM location: $(which pnpm)"
          echo "PATH: $PATH"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Semantic Release
        run: pnpm exec semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub-provided token
          
      - name: Notify Discord with changelog highlights
        if: success()
        env:
          DISCORD_RELEASE_WEBHOOK: ${{ secrets.DISCORD_RELEASE_WEBHOOK }}
        run: |
            LATEST_TAG=$(git describe --tags --abbrev=0)
        
            # Get recent changelog (adjust lines if needed)
            CHANGELOG=$(awk '/## 📦 Changelog/ {found=1} found' CHANGELOG.md | head -n 20 | sed 's/"/\\"/g')
        
            curl -H "Content-Type: application/json" \
              -X POST \
              -d @- "$DISCORD_RELEASE_WEBHOOK" <<EOF
            {
              "username": "ReleaseBot",
              "avatar_url": "https://i.imgur.com/bRMyEWh.png",
              "embeds": [
                {
                  "title": "📢 New Release: $LATEST_TAG",
                  "description": "$CHANGELOG",
                  "color": 5814783
                }
              ]
            }
            EOF
