name: Tag Release

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to fetch all tags and history

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest tag
        id: get_tag
        run: echo "TAG=$(git describe --tags --abbrev=0 --match 'v*' 2>/dev/null || echo 'v0.0.0')" >> $GITHUB_ENV

      - name: Determine new version
        id: versioning
        run: |
          OLD_TAG=${{ env.TAG }}
          echo "Previous tag: $OLD_TAG"

          if git log --format=%B -n 1 | grep -iqE "BREAKING CHANGE|major"; then
            TYPE="major"
          elif git log --format=%B -n 1 | grep -iqE "feat:"; then
            TYPE="minor"
          else
            TYPE="patch"
          fi

          MAJOR=$(echo $OLD_TAG | cut -d. -f1 | tr -d 'v')
          MINOR=$(echo $OLD_TAG | cut -d. -f2)
          PATCH=$(echo $OLD_TAG | cut -d. -f3)

          if [ "$TYPE" == "major" ]; then
            NEW_TAG="v$((MAJOR + 1)).0.0"
          elif [ "$TYPE" == "minor" ]; then
            NEW_TAG="v$MAJOR.$((MINOR + 1)).0"
          else
            NEW_TAG="v$MAJOR.$MINOR.$((PATCH + 1))"
          fi

          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "Versioning: $TYPE update to $NEW_TAG"

      - name: Check if tag already exists
        id: check_tag
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/${{ env.NEW_TAG }}$"; then
            echo "Tag already exists. Skipping release."
            echo "skip_release=true" >> $GITHUB_ENV
          else
            echo "skip_release=false" >> $GITHUB_ENV
        shell: bash

      - name: Create new tag
        if: env.skip_release != 'true'
        run: |
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}

      - name: Create GitHub Release
        if: env.skip_release != 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_TAG }}
          name: Release ${{ env.NEW_TAG }}
          body: "🚀 Automated release of ${{ env.NEW_TAG }}"
          draft: false
          prerelease: false

      - name: Notify Discord
        if: env.skip_release != 'true' && success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "📢 **New Release:** `${{ env.NEW_TAG }}` is now live! 🚀"}' \
               $DISCORD_WEBHOOK
